### ISSUE TITLE
"Remove all comments" - Setting

### ISSUE THREAD

**Issue by g-back** [fidley/ABAPQuickFix#14]
Hi,
thanks for this plugin, very useful!
A suggestion: add a setting to enable/disable the "Remove all comments" function (same as with the translation function). What do you think?

**Comment by fidley** [comment]
Hi, 
seams to be reasonable :) I will add it with next release.

Cheers
Łukasz

**Comment by fidley** [comment]
Almost perfect :) I also did the adaptations on my local repository with one or two bug solving.

From the code perspective it looks good, only one thing is that I've made it oposite, that defaulty it is switched on, as I don't want that people use to it would wander what happend.

I also made it outside the group for translation Quick fix, so it doesn't seems connected.

As you seems eager to get rid of this, it is published now, so you can get rid of it ;)

And thanks a lot for this contribution!

**Comment by fidley** [comment]
If you have more ideas please jump in :) And if you can tell me when you'll start with something, so I do not do the same thing :)

**Comment by MDagni** [comment]
I was wondering what's the idea behind this quick fix. Why would anyone want to remove "all" comments? Remove comments from selection might be useful and covers the other one.

**Comment by fidley** [comment]
That is my idea and I use it sometimes when dealing with old code. I don't like comments :)
