### ISSUE TITLE
Replace Operators

### ISSUE THREAD

**Issue by g-back** [fidley/ABAPQuickFix#18]
Idea for new quick fix: replace operators "EQ" "NE" with their "proper" counterparts.
I'd try this myself but there's a couple of traps:
- should not replace when in string literals or string templates
- should not replace in comments
- not in identifiers or keywords (obviously)

My regex abilities are unfortunately not good enough to handle those traps...

**Comment by fidley** [comment]
Nice one, it should not be that hard with regex, but maybe instead one, there will be a need to use more of the.

Will take a look on it.

**Comment by larshp** [comment]
something for testing, 

```abap
TYPES eq TYPE c.
DATA eq TYPE eq.
IF strlen( eq ) EQ eq AND eq EQ eq AND boolc( eq EQ eq ) EQ eq.
ENDIF.
```

**Comment by MDagni** [comment]
That would be impossible to solve :smile:

**Comment by fidley** [comment]
if compiler can handle this, then it is possible 😄  but maybe not with regex 😄

**Comment by fidley** [comment]
The list of keywords and functions that operators can appear in:

- IF
- CHECK
- WHILE
- SELECT
- COND 
- LOOP
- VALUE
- BOOLC

What else I miss? This could be starting point to check if in current statement one the keywords appear.

**Comment by larshp** [comment]
There is a where-used list in the bottom of https://syntax.abaplint.org/?filter=compare#/expression/CompareOperator, which might help, its ABAP there is always another special case, and note syntax.abaplint.org is also not complete but runs okay for a lot of code

**Comment by fidley** [comment]
Thanks Lars, I will go through it.
The other option would be to get the info directly from ADT editor, so far I haven't found the styled editor control, only plain text, but I will also deep dive into it.

**Comment by larshp** [comment]
tried to make an overview, https://syntax.abaplint.org/expression_CompareOperator_WhereUsed.svg, did not work out very well :)

**Comment by MDagni** [comment]
Is that where-used list for "eq" only?? That's huge!

**Comment by larshp** [comment]
yea, it is, basically EQ can be used inside `boolc`, and boolc can be used almost anywhere

**Comment by fidley** [comment]
I found the solution for this, but firstly I will finish the book and then I will implement this :)

**Comment by fidley** [comment]
I've created a new branch with the solution for this. So far using the old interfaces, but better that this would be splitted into separate solution, as it uses other technique.
Example of @larshp works perfectly. 

![EQ QuickFix](https://user-images.githubusercontent.com/7912195/112896615-e68be780-90de-11eb-81d6-b411a0a4da0d.gif)

**Comment by fidley** [comment]
Branch 1.0.13_EQ

**Comment by fidley** [comment]
is there a chance that someone will help me to redesign architecture of the StatementAssistProcessor to fit two scenarios, old using regex and new using internal ADT classes? I don't want to refactor everything as I don't have commitment from SAP about the internal classes that they will became API someday yet.

**Comment by fidley** [comment]
Relasesd with 1.0.13
