### ISSUE TITLE
Idea: Align equal signs (of selected rows)

### ISSUE THREAD

**Issue by g-back** [fidley/ABAPQuickFix#20]
Simple example:
```abap
    poheaderx = VALUE bapimepoheaderx(
        comp_code = abap_true
        doc_type = abap_true
        item_intvl = abap_true
        vendor = abap_true
        purch_org = abap_true
        pur_group = abap_true
        currency = abap_true
    ).
```
```abap
    poheaderx = VALUE bapimepoheaderx(
        comp_code  = abap_true
        doc_type   = abap_true
        item_intvl = abap_true
        vendor     = abap_true
        purch_org  = abap_true
        pur_group  = abap_true
        currency   = abap_true
    ).
```
Notes/Naive Approach/Ideas:
- only first equal sign of row is looked at (in case someone decides to use multiple per line, e.g for method calls)
- find "rightmost" equal sign in selected range, fill other rows with whitespace to align

**Comment by MDagni** [comment]
I would love to have this quick fix. I always spend time aligning those signs. And when a field's name changes, I have to align them again.. I wish pretty printer could do this.

**Comment by fidley** [comment]
Of course taking into consideration tabs and the sttings of editor (width of tab) in Preferences->General->Editors->Text Editors?

**Comment by fidley** [comment]
> I would love to have this quick fix. I always spend time aligning those signs. And when a field's name changes, I have to align them again.. I wish pretty printer could do this.

Probably this can be done on backend as well :) I've seen some enhancements to Pretty Printer on backend already, but I never used them.

**Comment by MDagni** [comment]
If you do this, we won't need the backend enhancement ;-) 

I believe you don't need to worry about tabs; Abap editor automatically converts all tabs to spaces.

**Comment by fidley** [comment]
Seems I have it. Works with operators : "EQ", "BT", "BETWEEN", "NE", "IN", "NOT", "IS", "CP", "CN", "CS", "NS", "LT",	"LE", "GE", "GT", "=", "<>", ">", "<", ">=", "<="

Does not matter if in select or other statements.

![QuickFixAlignOperators](https://user-images.githubusercontent.com/7912195/114751543-8e4b1b80-9d55-11eb-99da-d130630cf3fa.gif)

I need to do some more tests and then I'll publish it.

**Comment by fidley** [comment]
published

**Comment by g-back** [comment]
Works great, thanks! 👍 
Would you mind if I made a PR in the future with some small suggestions? Main purpose would be to get familiar with the codebase so I can maybe help you out in the future.

**Comment by fidley** [comment]
That would be great! I do a lot of dirty coding and usually it stays like
this forever. Any contribution is welcomed!

W dniu czw., 15.04.2021 o 17:55 g-back ***@***.***>
napisał(a):
