### ISSUE TITLE
Replace full line comment with in-line comment

### ISSUE THREAD

**Issue by g-back** [fidley/ABAPQuickFix#28]
Replace comments that start with `*` at the start of the line with inline-comments `"`
Unlike Full-Line Comments, Inline-comments are automatically indented, making them (imo) a lot easier to read.

Single Line or whole file (whole file: setting to be enabled)
Should be done easily with Regex since `*` has to be first character of line.

Will try this myself (if you give the ok)

**Comment by fidley** [comment]
> Will try this myself (if you give the ok)
Sure! thanks!

**Comment by MDagni** [comment]
> Single Line or whole file (whole file: setting to be enabled)

Instead of whole file, could you make it "for selected lines"? Because sometimes I use the * comments to separate sections, so I would like them to stay as they are, and replace others between them.

**Comment by g-back** [comment]
Yes, I think that's the better approach. Also the current implementation is a bit buggy, as it replaces ALL full line comments between statements. Will refactor it so it behaves more like  the "remove comments in selection" quick fix

**Comment by fidley** [comment]
This sounds like a good plan ;)
