### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by NeumannJoerg** [fidley/ABAPQuickFix#41]
Hi,

when I open the link for the [direct installtion](http://abapblog.com/eclipse/plugin/ABAPFavorites/) in the readme, I get an HTTP 403, from your server. This happens on my work notebook as well as on my private smartphone - so it doesn't seem to be a problem with the company firewall.
![2022-06-09 14_13_39-403 Forbidden und 1 weitere Seite - Profil 1 – Microsoft​ Edge](https://user-images.githubusercontent.com/86975244/172844239-ce82de09-4132-4731-b064-9726eec55d21.png)

When trying to install via drag&drop from [the marketplace](https://marketplace.eclipse.org/content/abap-quick-fix), the URL seems to be wrong.
![2022-06-09 14_10_53-Eclipse Marketplace](https://user-images.githubusercontent.com/86975244/172843805-6990eb37-1ccf-4fcc-b41a-7d4c3c8647a5.png)

If I continue anyways, I get the following error message.
![2022-06-09 14_12_12-Problem Occurred](https://user-images.githubusercontent.com/86975244/172843968-a10849c0-f41f-4242-b76f-2cdb5e7d7104.png)

Any advice?

Regards, 
Jörg

**Comment by fidley** [comment]
Hello Jörg,
when you click on the direct installation link from readme, it is normal that you have the 403 error, as it is not allow to anyone to browse the content of the folder on the server, but it is not a problem for eclipse installation.
It is also OK that at the end there is ABAPFavorites folder, as when I've started with my 1st plugin, which was ABAPFavorites, I wanted to know to people easier, that other plugins are also available, so I am using the same update site for all of my plugins.

Could you please check your network connection settings in Eclipse? As for me the update sites works correctly.
![5199C6CF-C357-4656-B214-947D3CCCA8EB](https://user-images.githubusercontent.com/7912195/172884656-a94a67bd-0553-4aa9-827f-001983e77b20.jpeg)
Maybe you have proxy in your company?

**Comment by NeumannJoerg** [comment]
Hello Łukasz,

thanks for your reply!

I tested again using a proxy and got the same result.
Then I tested it with my private PC and it worked like a charm!
So it seems to be some sort of network issue on my side.

Thanks anyway.


Regards, 
Jörg
