### ISSUE TITLE
New QuickFix : Uncombine statements

### ISSUE THREAD

**Issue by AlexandreHT** [fidley/ABAPQuickFix#44]
Hi, 

In order to implement CleanCode rule [Do not chain up-front declarations](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#do-not-chain-up-front-declarations), I would like to suggest a new quick fix for uncombining (or unchaining) statements.

Basically, it would be the exact opposite of the following rule: "Combine statements: DATA, TYPES, CONSTANTS, FIELD-SYMBOLS, CHECK, CLEAR, REFRESH, FREE, PARAMETERS, SELECT-OPTIONS, METHODS, CLASS-METHODS"

Thanks & Regards,
Alexandre

**Comment by fidley** [comment]
Hi,
It's already there in place 🙂, or?

Cheers
Łukasz

W dniu pt., 4.11.2022 o 11:55 AlexandreHT ***@***.***>
napisał(a):

**Comment by AlexandreHT** [comment]
Oups. Shame on me (and multitasking).
