### ISSUE TITLE
Installation for ADT 2022-09 doesn't work

### ISSUE THREAD

**Issue by aztechowski** [fidley/ABAPQuickFix#46]
I'm trying to install the plugin from https://marketplace.eclipse.org/content/abap-quick-fix and I'm receving following error:

Unable to read repository at https://fidley.github.io/ADTPluginsUpdateSite/UpdateSite/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

It's happen for all your plugins.

**Comment by fidley** [comment]
This is because of new requirement of Eclipse marketplace to have plugin update site stored under HTTPS. The easiest way to correct the issues is to add those two lines into eclipse.ini at the end.

-Djavax.net.ssl.trustStore=NONE
-Djavax.net.ssl.trustStoreType=Windows-ROOT

Other would be to download github certificates and add them to cert library of java.

**Comment by aztechowski** [comment]
The way with two lines at the end works perfecty.

**Comment by MartinH1337** [comment]
The lines fixed to install Favorites, but not for ADT ext and Quick Fix.
`An error occurred while collecting items to be installed
session context was:(profile=C__Users_xxx_eclipse_java-2022-06_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.abapblog.adt.quickfix,1.1.4.202308202221
No repository found containing: org.eclipse.update.feature,com.abapblog.adt.quickfix.feature,1.1.4.202308202221
No repository found containing: osgi.bundle,com.abapblog.adt.quickfix.release.notes.content,1.0.0.202308202221
No repository found containing: osgi.bundle,com.abapblog.branding,1.0.0.202308202221`
I am using 2023-03.
Any idea?

**Comment by fidley** [comment]
Hi @MartinH1337, that's strange behaviour, I was today installing all plugins on my new machine without issues.

Maybe you could try to download the update site to your PC. https://github.com/fidley/ADTPluginsUpdateSite the code is here. Just download the Update Site folder and use it in Eclipse for local plugin installation

![image](https://github.com/fidley/ABAPQuickFix/assets/7912195/517332a0-92c9-4bab-99c2-c452945be9c4)

**Comment by MartinH1337** [comment]
Thank you for your quick reply. 
I guess it is something like enterprise endpoint security or something. Whole eclipse went weird and update as well as fresh install also failed. Now I am back to middle ages until I get eclipse working again. My fault. No backup, no mercy. :-(
