### ISSUE TITLE
Split doesn't work with line comments

### ISSUE THREAD

**Issue by AlexandreHT** [fidley/ABAPQuickFix#50]
Hi, 
When I split the following instruction:
```ABAP
constants: foo type c value '0',  "foo
           bar type c value '1'.  "bar
```

I get the following result:
```ABAP
constants foo type c value '0'.
constants   "foobar type c value '1'.  "bar
```

Tested on Eclipse 2022-12 with Quick fix installed from Eclipse Marketplace. Not sure about the version since I got the release notes from 1.3 but when I look at the Eclipse MArketplace in the tab Installed, it's 1.0.16.

**Comment by fidley** [comment]
@AlexandreHT  could you please test with the version from the BETA update site? https://fidley.github.io/ADTPluginsUpdateSiteBeta/UpdateSite/

**Comment by AlexandreHT** [comment]
It works.

**Comment by fidley** [comment]
Relased to prod update site
