### ISSUE TITLE
New Quick Fix: Sort Declarations

### ISSUE THREAD

**Issue by lukas-mb** [fidley/ABAPQuickFix#58]
Hi, what do you think about a new quick fix for sorting data declarations? Sometimes, I encounter code with many declarations without any structure. There could also be an ordering mechanism based on user preferences. For example:
1. Objects (go_ , lo_)
2. Tables (gt_ , lt_)
3. Structures (gs_, ls_)
4. Data elements (gv_, lv_)

In the initial phase, we can use variable names for sorting, which is a simpler step. Later on, we could also implement a backend that searches for types in the dictionary, regardless of the variable name.

If I find some time in the upcoming weeks, I would try to start this myself.

**Comment by MDagni** [comment]
I love the idea! I usually want to do this manually, but you know, laziness... I agree with ordering mechanism; order by type if possible, order by name if not.

**Comment by fidley** [comment]
Sounds really great! If you need any support let me know.
