### ISSUE TITLE
Bug for quick fixing data statements

### ISSUE THREAD

**Issue by fsc-mrn** [fidley/ABAPQuickFix#62]
When using quick fix to combine/split data statements for variables that are referencing a type defined in a class(for example a type of a gateway entity) - the combine data statements suggestion is missing:
```
    DATA ls_entityset1 TYPE zcl_testapp_mpc=>ts_entity1.
    DATA ls_entityset2 TYPE zcl_testapp_mpc=>ts_entity1.
    DATA lv_matnr1     TYPE matnr.
    DATA lv_matnr2     TYPE matnr.
    DATA lv_matnr3     TYPE matnr.
```

If i just select the last 3 statements it works fine - i assume its due to a missing escaping of the special characters in this case?

Thanks in advance for checking!

Greetings
Marian

**Comment by fidley** [comment]
Thanks for the info @fsc-mrn it's been there since a while and no one noticed :-) Maybe it was not used ;)

**Comment by fsc-mrn** [comment]
Works perfectly! Thanks for the quick fix ;)

**Comment by fidley** [comment]
You're welcome
