### ISSUE TITLE
After using Sort QF, the last comment remains, and the one from the variable is added

### ISSUE THREAD

**Issue by fidley** [fidley/ABAPQuickFix#71]
That is strange. I can't reproduce it either...

I tested all versions 1.1.6.XXX and it works smoothly except the latest one (1.1.6.202406181410). Here I get an extra comment at the end, but the sorting still works:
![Animation](https://github.com/fidley/ABAPQuickFix/assets/147548956/4984e986-ea0d-4611-9360-c17f0707c59c)

_Originally posted by @lukas-mb in https://github.com/fidley/ABAPQuickFix/issues/67#issuecomment-2178936129_

**Comment by fidley** [comment]
@lukas-mb should be now solved.
I need to invest time to include UnitTests here ;)

**Comment by lukas-mb** [comment]
Yes it's working on my side again. Thank you!
