### ISSUE TITLE
Discussion: How to activate all Inactives

### ISSUE THREAD

**Issue by pardonmycode** [fidley/ABAPQuickFix#75]
Hi Fdiley,
I really appreciate your work, which inspired me to develop an Eclipse Plugin. However, I've encountered an issue:

I need to activate all inactive objects without using the `command com.sap.adt.activation.ui.command.multiActivation` because it requires additional input.

Here's what I'm trying:
```
factory = AdtActivationPlugin.getDefault().getActivationServiceFactory();
activationService = factory.createActivationService(project.getName());
newInactiveCtsObjectList = activationService.getInactiveCtsObjects(new NullProgressMonitor());
```
Despite this, I'm unable to activate `newInactiveCtsObjectList`. Could you provide guidance on how to proceed?

**Comment by fidley** [comment]
Hi @pardonmycode ,

glad to hear that I was inspiration :)

The newInactiveCtsObjectList is an array of IInactiveCtsObject, which have the method getObject() which returns IWorkingObject.

From there you should get the reference to IAdtObjectReference
![image](https://github.com/fidley/ABAPQuickFix/assets/7912195/6829132c-2859-4b15-a1a2-e91a0520167c)

Build a list from all then then use activationService.activate( your IAdtObjectReference list).

As long as it is possible to do so.

**Comment by pardonmycode** [comment]
Hi :)
The Problem is:
difference in `IAdtObjectReference`:
`com.sap.adt.tools.core.IAdtObjectReference`
`com.sap.adt.tools.core.model.adtcore.IAdtObjectReference`

``` activationService.activate(List<IAdtObjectReference>  adtRefs); ```
except `IAdtObjectReference` of `com.sap.adt.tools.core.IAdtObjectReference`
but `IInactiveCtsObject`is from
`com.sap.adt.tools.core.model.adtcore.IAdtObjectReference`

and cast is also no possible:
`java.lang.ClassCastException:` 
`class com.sap.adt.tools.core.model.adtcore.impl.AdtObjectReferenceImpl` 
`cannot be cast to `
`class com.sap.adt.tools.core.IAdtObjectReference`

**Comment by fidley** [comment]
Maybe check the adapters?
![image](https://github.com/fidley/ABAPQuickFix/assets/7912195/33633c59-6266-49b0-9a61-7b9cd061af51)

**Comment by pardonmycode** [comment]
couldn`t do it, but Thank you for your help.

**Comment by pardonmycode** [comment]
Do you any documentation of "com.sap.adt.* " ?

**Comment by fidley** [comment]
Only this what is found under https://tools.eu1.hana.ondemand.com/additional/com.sap.adt.core.apidoc-3.42.1.zip 

https://tools.eu1.hana.ondemand.com/#abap
![image](https://github.com/user-attachments/assets/4b3c38ff-60ed-414a-a111-db099fe12ebd)

The rest I always search using the project where I have all adt plugins added as dependency and then I read it using Enhanced Class Decompiler and I search using the names with standard Eclipse functions on plugin development perspective.
